import React, { useState, useContext } from 'react';
import api from '../services/api';
import Layout from '../components/Layout';
import { AuthContext } from '../context/AuthContext';

const ActionPlan = () => {
  const { user } = useContext(AuthContext);
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const generatePlan = async () => {
    setLoading(true);
    try {
      const activitiesRes = await api.get('/activities');
      const activities = activitiesRes.data;

      if (activities.length === 0) {
        alert('Please log some activities first so the AI can personalize your plan.');
        setLoading(false);
        return;
      }

      const res = await api.post('/ai/eco-plan', { activities });
      setPlan(res.data.plan);
    } catch (err) {
      alert(err.response?.data?.message || 'Error generating plan. Is the backend running?');
    }
    setLoading(false);
  };

  // Default plan shown while user hasn't generated yet
  const sampleDays = [
    { day: 'Day 1', action: 'Use public transport or walk instead of driving', icon: '🚌' },
    { day: 'Day 2', action: 'Switch off unused appliances and lights', icon: '💡' },
    { day: 'Day 3', action: 'Eat a plant-based meal — skip meat for one day', icon: '🥗' },
    { day: 'Day 4', action: 'Avoid single-use plastics — bring a reusable bag', icon: '♻️' },
    { day: 'Day 5', action: 'Take a shorter shower and save water', icon: '💧' },
    { day: 'Day 6', action: 'Sort waste and recycle correctly', icon: '🗑️' },
    { day: 'Day 7', action: 'Share your eco progress with a friend or family member', icon: '🌍' },
  ];

  return (
    <Layout>
      <h1 style={{ fontFamily: 'Outfit, sans-serif', fontSize: '2rem', marginBottom: '8px' }}>
        Eco Action Plan
      </h1>
      <p style={{ color: 'var(--text-muted)', marginBottom: '32px' }}>
        Get a personalized 7-day sustainability plan generated by Gemini AI based on your
        logged activities.
      </p>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }}>
        {/* Generator Panel */}
        <div className="glass-panel" style={{ alignSelf: 'start' }}>
          <h3 style={{ marginBottom: '16px' }}>✨ Generate Your Plan</h3>
          <p style={{ color: 'var(--text-muted)', lineHeight: 1.7, marginBottom: '24px' }}>
            CarbonWise AI will analyze your logged activities and create a personalized
            weekly eco-action plan with practical, achievable steps tailored to your
            lifestyle.
          </p>

          <div
            style={{
              padding: '16px',
              borderRadius: '10px',
              background: 'rgba(16,185,129,0.08)',
              border: '1px solid rgba(16,185,129,0.2)',
              marginBottom: '24px',
            }}
          >
            <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
              💡 <strong style={{ color: 'var(--text-main)' }}>Tip:</strong> Log at least 3–5
              activities in the Activity Tracker for a more accurate and personalized AI plan.
            </p>
          </div>

          <button
            className="btn"
            onClick={generatePlan}
            disabled={loading}
          >
            {loading ? '🤖 Generating with Gemini...' : '🌱 Generate My Eco Plan'}
          </button>

          {plan && (
            <button
              className="btn"
              style={{
                marginTop: '12px',
                background: 'transparent',
                border: '1px solid var(--surface-border)',
                color: 'var(--text-muted)',
              }}
              onClick={() => setPlan(null)}
            >
              Clear Plan
            </button>
          )}
        </div>

        {/* Plan Display */}
        <div className="glass-panel">
          <h3 style={{ marginBottom: '20px' }}>
            {plan ? `🌍 Your Personalized Plan — ${user?.name}` : '📅 Sample Weekly Plan'}
          </h3>

          {plan ? (
            <div
              style={{
                background: 'rgba(0,0,0,0.2)',
                padding: '20px',
                borderRadius: '10px',
                lineHeight: 1.8,
                whiteSpace: 'pre-wrap',
                color: 'var(--text-muted)',
                fontSize: '0.95rem',
                maxHeight: '500px',
                overflowY: 'auto',
              }}
            >
              {plan}
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {sampleDays.map((d) => (
                <div
                  key={d.day}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '16px',
                    padding: '14px 16px',
                    borderRadius: '10px',
                    background: 'rgba(0,0,0,0.2)',
                    border: '1px solid var(--surface-border)',
                  }}
                >
                  <span style={{ fontSize: '1.5rem' }}>{d.icon}</span>
                  <div>
                    <div
                      style={{ fontSize: '0.75rem', color: 'var(--primary)', fontWeight: 600, marginBottom: '2px' }}
                    >
                      {d.day}
                    </div>
                    <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>{d.action}</div>
                  </div>
                </div>
              ))}
              <p
                style={{
                  marginTop: '8px',
                  fontSize: '0.8rem',
                  color: 'var(--text-muted)',
                  fontStyle: 'italic',
                  textAlign: 'center',
                }}
              >
                This is a generic sample. Generate your personalized AI plan above.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Impact Goals */}
      <div className="glass-panel" style={{ marginTop: '32px' }}>
        <h3 style={{ marginBottom: '20px' }}>🎯 Impact Goals</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          {[
            { goal: 'Reduce transport emissions by 30%', icon: '🚗', difficulty: 'Medium' },
            { goal: 'Switch to energy-saving appliances', icon: '⚡', difficulty: 'Easy' },
            { goal: 'Eat plant-based 3x per week', icon: '🥗', difficulty: 'Easy' },
            { goal: 'Zero single-use plastic for a week', icon: '♻️', difficulty: 'Hard' },
          ].map((item) => (
            <div
              key={item.goal}
              style={{
                padding: '16px',
                borderRadius: '10px',
                background: 'rgba(0,0,0,0.2)',
                border: '1px solid var(--surface-border)',
                textAlign: 'center',
              }}
            >
              <div style={{ fontSize: '2rem', marginBottom: '8px' }}>{item.icon}</div>
              <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '8px', lineHeight: 1.4 }}>
                {item.goal}
              </p>
              <span
                style={{
                  fontSize: '0.75rem',
                  padding: '3px 10px',
                  borderRadius: '12px',
                  background:
                    item.difficulty === 'Easy'
                      ? 'rgba(16,185,129,0.15)'
                      : item.difficulty === 'Medium'
                      ? 'rgba(245,158,11,0.15)'
                      : 'rgba(239,68,68,0.15)',
                  color:
                    item.difficulty === 'Easy'
                      ? '#10b981'
                      : item.difficulty === 'Medium'
                      ? '#f59e0b'
                      : '#ef4444',
                }}
              >
                {item.difficulty}
              </span>
            </div>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export default ActionPlan;
